<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>_01_LampshadeQuery</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiscountManagment.Infrastructure.EFCore\DiscountManagment.Infrastructure.EFCore.csproj" />
    <ProjectReference Include="..\InventoryManagment.Infrastructure.EFCore\InventoryManagment.Infrastructure.EFCore.csproj" />
    <ProjectReference Include="..\ShopManagment.Infrastructure.EFCore\ShopManagment.Infrastructure.EFCore.csproj" />
  </ItemGroup>

</Project>
