<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventoryManagment.Application.Contract\InventoryManagment.Application.Contract.csproj" />
    <ProjectReference Include="..\InventoryManagment.Domain\InventoryManagment.Domain.csproj" />
  </ItemGroup>

</Project>
